[[group]]

[group.source]
frequency = 220.0
op_kind = "Square"

[[group.operators]]
frequency = 4.0
op_kind = "Sine"

[group.operators.stepper]
bpm = 60
steps = [
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqMult", val = 1.5 },
    { kind = "Nop" },
    { kind = "FreqSet", val = 4.0 },
]

[[group.operators]]
frequency = 2.0
op_kind = "Sine"

[[group]]
source = { frequency = 440.0, op_kind = "Square" }
operators = [
    { frequency = 8.0, op_kind = "Sine" },
    { frequency = 0.5, op_kind = "Saw", phase_steps = 12000 },
]

[[group]]
operators = [
    { frequency = 1.0, op_kind = "Sine" },
    { frequency = 0.25, op_kind = "Sine" },
]

[group.source]
frequency = 110.0
op_kind = "Saw"

[group.source.stepper]
bpm = 60
steps = [
    { kind = "FreqSet", val = 110.0 },
    { kind = "Nop" },
    { kind = "FreqSet", val = 220.0 },
    { kind = "FreqSet", val = 440.0 },
]
